execute pathogen#infect()

syntax on
filetype on
filetype plugin on
filetype plugin indent on

set backspace=2
set autoindent
set cindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set list
set listchars=tab:>-,trail:-
set paste
set expandtab
set number
set ruler
set cursorline
set laststatus=2
set statusline=%F%m%r%h%w\ [%{&ff}\ %{(&fenc==\"\"?&enc:&fenc).(&bomb?\",BOM\":\"\")}]\ [ASC=\%03.3b]\ [HEX=\%02.2B]\ [%04l,%04v][%p%%]\ [LEN=%L]
set hlsearch
set fileencodings=utf-8,gbk

autocmd BufReadPost *.go,*.php,*.py call tagbar#autoopen()

" go get -u github.com/jstemmer/gotags

let g:tagbar_type_go = {
    \ 'ctagstype' : 'go',
    \ 'kinds'     : [
        \ 'p:package',
        \ 'i:imports:1',
        \ 'c:constants',
        \ 'v:variables',
        \ 't:types',
        \ 'n:interfaces',
        \ 'w:fields',
        \ 'e:embedded',
        \ 'm:methods',
        \ 'r:constructor',
        \ 'f:functions'
    \ ],
    \ 'sro' : '.',
    \ 'kind2scope' : {
        \ 't' : 'ctype',
        \ 'n' : 'ntype'
    \ },
    \ 'scope2kind' : {
        \ 'ctype' : 't',
        \ 'ntype' : 'n'
    \ },
    \ 'ctagsbin'  : '~/.vim/bin/gotags',
    \ 'ctagsargs' : '-sort -silent'
\ }
